import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { atomicWriteFileSync, backupExisting } from "../util/backup.js";
import {
  EDEN_DEFAULTS,
  EDEN_ENV_FIELDS,
  health,
  resolveEdenOptions,
  getMissingRequiredEnvFields,
} from "../memory/eden-memory.js";
import { formatCommandWarning } from "../ui/display-grammar.js";

const ENV_HEADER = `# Project-level ATP environment configuration
# Generated by pi-agents-team /team-env. Safe to edit by hand.
`;

const FIELD_DESCRIPTIONS = {
  [EDEN_ENV_FIELDS.BIN]: "eden-memory binary path",
  [EDEN_ENV_FIELDS.ENABLED]: "eden-memory integration enabled flag",
  [EDEN_ENV_FIELDS.DB]: "eden-memory SQLite database path",
  [EDEN_ENV_FIELDS.WORKSPACE_ID]: "workspace scope id",
  [EDEN_ENV_FIELDS.USER_ID]: "user identity",
  [EDEN_ENV_FIELDS.AGENT_ID]: "agent identity",
  [EDEN_ENV_FIELDS.SEMANTIC_SEARCH]: "semantic-search enabled flag",
  [EDEN_ENV_FIELDS.LLM_API_KEY]: "LLM API key for semantic search",
  [EDEN_ENV_FIELDS.LLM_BASE_URL]: "LLM base URL for semantic search",
};

const EDEN_FIELD_NAMES = new Set(Object.values(EDEN_ENV_FIELDS));

function readEnvFile(path) {
  if (!existsSync(path)) return {};
  const text = readFileSync(path, "utf8");
  const parsed = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    parsed[key] = value;
  }
  return parsed;
}

function escapeEnvValue(value) {
  return value.replace(/\n/g, "\\n").replace(/\r/g, "\\r");
}

function buildEnvContents(entries) {
  const lines = [ENV_HEADER];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`${key}=${escapeEnvValue(value)}`);
  }
  lines.push("");
  return lines.join("\n");
}

function applyEnvToProcessEnv(entries) {
  for (const [key, value] of Object.entries(entries)) {
    if (EDEN_FIELD_NAMES.has(key)) {
      process.env[key] = value;
    }
  }
}

function mergeWithDefaults(entries) {
  const merged = {
    [EDEN_ENV_FIELDS.BIN]: entries[EDEN_ENV_FIELDS.BIN] ?? EDEN_DEFAULTS.bin,
    [EDEN_ENV_FIELDS.ENABLED]: entries[EDEN_ENV_FIELDS.ENABLED] ?? EDEN_DEFAULTS.enabled,
    [EDEN_ENV_FIELDS.DB]: entries[EDEN_ENV_FIELDS.DB] ?? EDEN_DEFAULTS.db,
    [EDEN_ENV_FIELDS.WORKSPACE_ID]: entries[EDEN_ENV_FIELDS.WORKSPACE_ID] ?? EDEN_DEFAULTS.workspaceId,
    [EDEN_ENV_FIELDS.USER_ID]: entries[EDEN_ENV_FIELDS.USER_ID] ?? EDEN_DEFAULTS.userId,
    [EDEN_ENV_FIELDS.AGENT_ID]: entries[EDEN_ENV_FIELDS.AGENT_ID] ?? EDEN_DEFAULTS.agentId,
    [EDEN_ENV_FIELDS.SEMANTIC_SEARCH]: entries[EDEN_ENV_FIELDS.SEMANTIC_SEARCH] ?? EDEN_DEFAULTS.semanticSearch,
    ...entries,
  };
  return merged;
}

/**
 * Prompt the user for missing required fields. Returns the updated entries or
 * undefined if the user cancelled.
 */
async function promptMissingFields(ctx, entries, missing) {
  if (!ctx.hasUI || !ctx.ui) return undefined;
  const prompts = {
    [EDEN_ENV_FIELDS.BIN]: { label: "eden-memory binary path", defaultValue: entries[EDEN_ENV_FIELDS.BIN] ?? EDEN_DEFAULTS.bin },
    [EDEN_ENV_FIELDS.DB]: { label: "eden-memory SQLite database path", defaultValue: entries[EDEN_ENV_FIELDS.DB] ?? EDEN_DEFAULTS.db },
    [EDEN_ENV_FIELDS.WORKSPACE_ID]: { label: "Workspace ID", defaultValue: entries[EDEN_ENV_FIELDS.WORKSPACE_ID] ?? EDEN_DEFAULTS.workspaceId },
    [EDEN_ENV_FIELDS.USER_ID]: { label: "User ID", defaultValue: entries[EDEN_ENV_FIELDS.USER_ID] ?? EDEN_DEFAULTS.userId },
    [EDEN_ENV_FIELDS.AGENT_ID]: { label: "Agent ID", defaultValue: entries[EDEN_ENV_FIELDS.AGENT_ID] ?? EDEN_DEFAULTS.agentId },
    [EDEN_ENV_FIELDS.LLM_API_KEY]: { label: "LLM API key for semantic search", defaultValue: entries[EDEN_ENV_FIELDS.LLM_API_KEY] ?? "", sensitive: true },
    [EDEN_ENV_FIELDS.LLM_BASE_URL]: { label: "LLM base URL for semantic search", defaultValue: entries[EDEN_ENV_FIELDS.LLM_BASE_URL] ?? "" },
  };
  const updated = { ...entries };
  for (const field of missing) {
    const prompt = prompts[field];
    const answer = await ctx.ui.input(`${prompt.label}:`, prompt.defaultValue);
    if (answer === null || answer === undefined) {
      const cancelled = await ctx.ui.confirm("Cancel /team-env?", "A required field was skipped; stop writing the .env file.");
      if (cancelled) return undefined;
      continue;
    }
    updated[field] = answer.trim() || prompt.defaultValue;
  }
  return updated;
}

function findProjectEnvPath(cwd) {
  return resolve(cwd, ".env");
}

function findProjectGitignorePath(cwd) {
  return resolve(cwd, ".gitignore");
}

function envIsAlreadyIgnored(gitignorePath) {
  if (!existsSync(gitignorePath)) return false;
  const text = readFileSync(gitignorePath, "utf8");
  for (const raw of text.split("\n")) {
    const line = raw.split("#")[0].trim();
    if (!line) continue;
    if (line === ".env") return true;
    // A pattern like .env*, .env/, or .env? also covers the file.
    if (line.startsWith(".env") && /[\/*?]/.test(line.slice(4, 5))) return true;
  }
  return false;
}

function ensureEnvIgnored(cwd) {
  const gitignorePath = findProjectGitignorePath(cwd);
  if (envIsAlreadyIgnored(gitignorePath)) return false;
  let prefix = "";
  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, "utf8");
    if (existing.length > 0 && !existing.endsWith("\n")) prefix = "\n";
  }
  appendFileSync(gitignorePath, `${prefix}.env\n`);
  return true;
}

function describeFieldName(name) {
  return FIELD_DESCRIPTIONS[name] ?? name;
}

function formatMissingFieldsReport(missing) {
  if (missing.length === 0) return "All required eden-memory env fields are present.";
  const lines = missing.map((name) => `- ${name}: ${describeFieldName(name)}`);
  return `Missing required eden-memory env fields:\n${lines.join("\n")}`;
}

export async function runEnvWizard(ctx, force = false) {
  const envPath = findProjectEnvPath(ctx.cwd);
  const existed = existsSync(envPath);
  let entries = readEnvFile(envPath);
  const missingBefore = getMissingRequiredEnvFields(entries);
  const report = [];
  report.push(existed ? `Project .env found at ${envPath}.` : `No project .env at ${envPath}.`);
  report.push(formatMissingFieldsReport(missingBefore));

  if (missingBefore.length === 0 && !force) {
    report.push("Everything is already configured. Use /team-env --force to overwrite values, or edit the file by hand.");
    return { updated: false, envPath, missingBefore, missingAfter: [], report };
  }

  entries = mergeWithDefaults(entries);
  let missingAfter = getMissingRequiredEnvFields(entries);

  if (missingAfter.length > 0 && ctx.hasUI && ctx.ui) {
    const ok = await ctx.ui.confirm(
      "Create /team-env .env?",
      `${missingAfter.length} required eden-memory value(s) missing. Fill them in now?`,
    );
    if (ok) {
      const answered = await promptMissingFields(ctx, entries, missingAfter);
      if (answered) {
        entries = answered;
      }
    }
  }

  missingAfter = getMissingRequiredEnvFields(entries);
  if (missingAfter.length > 0) {
    report.push("Could not collect all required fields. .env was not written.");
    return { updated: false, envPath, missingBefore, missingAfter, report };
  }

  mkdirSync(dirname(envPath), { recursive: true });
  if (existed) {
    const backupPath = backupExisting(envPath);
    report.push(`Backed up previous .env to ${backupPath}.`);
  }
  atomicWriteFileSync(envPath, buildEnvContents(entries), { mode: 0o600 });
  applyEnvToProcessEnv(entries);
  const gitignoreUpdated = ensureEnvIgnored(ctx.cwd);
  report.push(`Wrote ${envPath}.`);
  if (gitignoreUpdated) {
    report.push(`Added .env to ${findProjectGitignorePath(ctx.cwd)}.`);
  }
  report.push("Env vars are now active in the current session.");

  // Surface lock conflicts immediately so the user knows to stop a conflicting
  // eden-memory process before writes can succeed.
  const options = resolveEdenOptions(entries);
  const healthResult = await health(options);
  if (!healthResult.ok) {
    if (healthResult.locked) {
      report.push(`Warning: ${options.db} is locked by another eden-memory process. Stop the other process before memory writes will succeed.`);
    } else {
      report.push(`Warning: eden-memory health check failed: ${healthResult.error}`);
    }
  } else {
    report.push("eden-memory health check passed.");
  }

  return { updated: true, envPath, missingBefore, missingAfter: [], report };
}

export function parseEnvArgs(args) {
  const tokens = args.trim().split(/\s+/).filter(Boolean);
  let force = false;
  let checkOnly = false;
  for (const token of tokens) {
    if (token === "--force" || token === "-f") {
      force = true;
      continue;
    }
    if (token === "--check" || token === "-c") {
      checkOnly = true;
      continue;
    }
    return { error: `Unknown argument: ${token}. Expected --force or --check.` };
  }
  return { force, checkOnly };
}

export function buildEnvCommandCompletions(prefix) {
  const hasTrailingSpace = /\s$/.test(prefix);
  const tokens = prefix.trim().split(/\s+/).filter(Boolean);
  const currentToken = hasTrailingSpace ? "" : (tokens.at(-1) ?? "");
  return ["--force", "--check"]
    .filter((value) => !tokens.includes(value) && value.startsWith(currentToken))
    .map((value) => ({
      value,
      label: value,
      description: value === "--force" ? "Overwrite existing values" : "Report missing fields without writing",
    }));
}

export function registerTeamEnvCommand(pi) {
  pi.registerCommand("team-env", {
    description: "Check or create the project .env for eden-memory ATP settings: /team-env [--check|--force]",
    getArgumentCompletions: (prefix) => buildEnvCommandCompletions(prefix),
    handler: async (args, ctx) => {
      const parsed = parseEnvArgs(args);
      if (parsed.error) {
        if (ctx.ui) ctx.ui.notify(formatCommandWarning(parsed.error), "warning");
        else console.error(parsed.error);
        return;
      }
      if (parsed.checkOnly) {
        const envPath = findProjectEnvPath(ctx.cwd);
        const entries = readEnvFile(envPath);
        const missing = getMissingRequiredEnvFields(entries);
        const lines = [existsSync(envPath) ? `Project .env found at ${envPath}.` : `No project .env at ${envPath}.`, formatMissingFieldsReport(missing)];
        const text = lines.join("\n");
        if (ctx.ui) ctx.ui.notify(text, missing.length > 0 ? "warning" : "info");
        else console.log(text);
        return;
      }
      const result = await runEnvWizard(ctx, parsed.force);
      const text = result.report.join("\n");
      if (ctx.ui) {
        const level = result.missingAfter.length > 0 ? "warning" : "info";
        ctx.ui.notify(text, level);
      }
      else console.log(text);
    },
  });
}

export const _testing = {
  buildEnvContents,
  describeFieldName,
  escapeEnvValue,
  findProjectEnvPath,
  formatMissingFieldsReport,
  mergeWithDefaults,
  parseEnvArgs,
  promptMissingFields,
  readEnvFile,
  runEnvWizard,
  ensureEnvIgnored,
  envIsAlreadyIgnored,
  findProjectGitignorePath,
  applyEnvToProcessEnv,
};
