import type { Theme } from "@earendil-works/pi-coding-agent";
export declare const bold: (text: string) => string;
export declare const dim: (text: string) => string;
export declare const muted: (text: string) => string;
export declare const accent: (text: string) => string;
export declare const accentBold: (text: string) => string;
export declare const success: (text: string) => string;
export declare const successBold: (text: string) => string;
export declare const warning: (text: string) => string;
export declare const warningBold: (text: string) => string;
export declare const danger: (text: string) => string;
export declare const dangerBold: (text: string) => string;
export declare const inverse: (text: string) => string;
export interface ThemedPalette {
    bold: (text: string) => string;
    dim: (text: string) => string;
    muted: (text: string) => string;
    accent: (text: string) => string;
    accentBold: (text: string) => string;
    success: (text: string) => string;
    successBold: (text: string) => string;
    warning: (text: string) => string;
    warningBold: (text: string) => string;
    danger: (text: string) => string;
    dangerBold: (text: string) => string;
    inverse: (text: string) => string;
}
export declare const fallbackPalette: ThemedPalette;
export declare function themedPalette(theme?: Theme): ThemedPalette;
export declare const FRAME: {
    readonly topLeft: "╭";
    readonly topRight: "╮";
    readonly bottomLeft: "╰";
    readonly bottomRight: "╯";
    readonly horizontal: "─";
    readonly vertical: "│";
    readonly teeRight: "├";
    readonly teeLeft: "┤";
};
export declare function stripAnsi(text: string): string;
export declare function sanitizeTerminalText(text: string): string;
